// scripts/generate_dependencies.dart

import 'dart:io';
import 'package:yaml/yaml.dart';

void main() {
  final lockFile = File('pubspec.lock');
  if (!lockFile.existsSync()) {
    print('pubspec.lock not found.');
    exit(1);
  }

  final pubspecLockContent = lockFile.readAsStringSync();
  final pubspecLock = loadYaml(pubspecLockContent) as YamlMap;

  final packages = pubspecLock['packages'] as YamlMap;

  final buffer = StringBuffer();

  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln(
      '// This file is generated by scripts/generate_dependencies.dart');
  buffer.writeln('');
  buffer.writeln('const Map<String, String> dependencies = {');

  packages.forEach((packageName, packageInfo) {
    final version = packageInfo['version'];
    buffer.writeln("  '$packageName': '$version',");
  });

  buffer.writeln('};');

  final outputFile = File('lib/generated/dependencies.dart');
  outputFile.writeAsStringSync(buffer.toString());

  print('Generated lib/generated/dependencies.dart');
}
